IShareMVCFinal/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IShareMVCFinal.DAO;
using IShareMVCFinal.Models.Tables;
using IShareMVCFinal.Models.ViewModels;

namespace IShareMVCFinal.Controllers
{
    public class NotesController : Controller
    {
        
        public ActionResult Create()
        {
            var cookieId = Request.Cookies["userId"];
            string userId = "";

            if (cookieId != null)
            {
                userId = cookieId.Value;
                var user = UserDAO.GetUser(int.Parse(userId));
                var note = new Note();
                
                var createItem = new CreateNoteUserModelView
                {
                    UserItem = user,
                    NoteItem = note                   
                };
                return View(createItem);
            }
            return View();
        }

        [HttpPost]
        public ActionResult Create(Note note)
        {
            try
            {
             
                NoteDAO.Create(note);
                //get tags
                var tagList = note.TagList;
                char[] delimiter = {' '};                
                string[] tags = tagList.Split(delimiter);

               foreach (var tag in tags)
                {                    
                    if(tag != null || tag != "")
                    {
                        var t = new Tag
                        {
                            Name = tag
                        };
                        TagDAO.Create(t);
                    }
                    
                    var tagItem = TagDAO.GetTag(tag);
                    var nTag = new Note_Tag();
                    nTag.NoteId = note.NoteId;
                    nTag.TagId = tagItem.Id;                    
                    Note_TagDAO.Create(nTag);
                }
               
               return RedirectToAction("Index", "Home");             
            }
            catch
            {
                return RedirectToAction("Index", "Home");
                return View();
            }

            return RedirectToAction("Index", "Home");
        }

    }
}

IShareMVCFinal/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IShareMVCFinal.DAO;
using IShareMVCFinal.Models.Tables;
using IShareMVCFinal.Models.ViewModels;

namespace IShareMVCFinal.Controllers
{
    public class UsersController : Controller
    {
        public ActionResult Register()
        {
            return View();
        }
              
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(User user)
        {
            UserDAO.Create(user);
            return Redirect("Login");
        }

        [HttpPost]
        public ActionResult Login(User user)
        {
            var activeUser = UserDAO.GetUser(user);
            if (activeUser != null)
            {
                var userCookie = new HttpCookie("userId", activeUser.Id.ToString());
                Response.AppendCookie(userCookie);
                return RedirectToAction("Index", "Home");
            }
            return Redirect("Login");
        }

        public ActionResult Account()
        {
            var cookieId = Request.Cookies["userId"];
            string userId = "";

            if (cookieId != null)
            {
                userId = cookieId.Value;
                var user = UserDAO.GetUser(int.Parse(userId));
                var likedList = NoteDAO.GetLikedPosts(user.Id);
                var repostedist = NoteDAO.GetRepostedNotes(user.Id);
                var originalPosts = NoteDAO.GetOriginalPosts(user.Id);
                
                var accountViewItem = new AccountViewModel
                {
                    LikedNotes = likedList,
                    RepostedNotes = repostedist,
                    OriginalNotes = originalPosts            
                };

                return View(accountViewItem);
            } 
              
            return View();
        }


        public ActionResult AllUsers()
        {
            var users = UserDAO.GetUsers();
            return View(users);
        }


        public ActionResult UserAccount(int id)
        {
            if (id != 0)
            {
                var user = UserDAO.GetUser(id);
                var likedList = NoteDAO.GetLikedPosts(user.Id);
                var repostedist = NoteDAO.GetRepostedNotes(user.Id);
                var originalPosts = NoteDAO.GetOriginalPosts(user.Id);

                var accountViewItem = new AccountViewModel
                {
                    LikedNotes = likedList,
                    RepostedNotes = repostedist,
                    OriginalNotes = originalPosts
                };

                return View(accountViewItem);
            }

            return View();
        }




    }
}

IShareMVCFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
   

<style type="text/css">
    @@font-face
    {
        font-family: 'TSTARBold'; 
        src: url('/TSTAR-TW-PRO-Bold-1.ttf'); 
    }
    @@font-face
    {
        font-family: 'TSTARRegular'; 
        src: url('/TSTAR-TW-PRO-Regular-1.ttf'); 
    }
    .tsarB 
    {
        font-family: 'TSTARBold';
    }
    .tsarR 
    {
        font-family: 'TSTARRegular';
    }
    .robo {
        font-family: 'Roboto', sans-serif;
    }

</style>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">


            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("IShare", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="hidden navItems">@Html.ActionLink("News", "ParseNews", "Home")</li>
                    <li class="hidden navItems">@Html.ActionLink("Add Note", "Create", "Notes")</li>
                    <li class="hidden navItems">@Html.ActionLink("My Account", "Account", "Users")</li>   
                    <li class="hidden navItems">@Html.ActionLink("View All Users", "AllUsers", "Users")</li>
                    <li class="hidden navItems">@Html.ActionLink("Log out", "LogOut", "Home")</li>     
                </ul>

            </div>

        </div>
    </div>

<div class="container body-content">
    @RenderBody()
    <hr/>

</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>